_core:
  default_config_hash: gMIuS6XMaAXGl0g6aF1RHZWAez7xTIDY8quVCUmk5Eo
api_key: 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
activate_marketing_automation: false
client_key: ''
