_core:
  default_config_hash: fPJJWwxlnLsBCil38XO7xl2EG51V11Yktsk_hC6ynTc
langcode: en
auto_decorate_final_html: 0
auto_decorate_js_alter: 1
auto_decorate_page_attachments: 1
block_unknown: 0
block_unknown_logger: 0
block_unknown_label: 'Unknown Apps'
block_unknown_description: 'Block unknown external resources'
show_toggle_button: true
deletable_cookie_domains: {  }
exclude_urls: {  }
disable_urls: {  }
styles:
  - ''
process_descriptions: false
library:
  element_id: klaro
  storage_method: cookie
  cookie_name: klaro
  cookie_expires_after_days: 1
  cookie_domain: ''
  group_by_purpose: false
  must_consent: true
  accept_all: false
  hide_decline_all: false
  hide_learn_more: false
  learn_more_as_button: false
  notice_as_modal: true
  additional_class: ''
  html_texts: false
