_core:
  default_config_hash: tKLBW2GXZVLFXqS9QgLyfTuxCLc1u_quKPQLtCia-Bw
entity_type_groups:
  node:
    article:
      basic: basic
      schema_article: schema_article
    person:
      basic: basic
      schema_person: schema_person
  taxonomy_term:
    tags:
      basic: basic
separator: ','
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
tag_scroll_max_height: ''
