_core:
  default_config_hash: 3mgYDspyj5REgG6ooA1izlcMzEs34kHPFUOMIXeDOco
entity_type_groups:
  node:
    person:
      basic: basic
      advanced: advanced
    article:
      basic: basic
      advanced: advanced
    page:
      basic: basic
      advanced: advanced
    organization:
      basic: basic
      advanced: advanced
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength: {  }
tag_scroll_max_height: ''
