_core:
  default_config_hash: M4h8NZak4uD9gCKWadu5xkNXUg2BReEFe_eKd9AHln4
default_properties:
  - episode
  - hasCourseInstance
default_form_displays:
  - Episode
  - Course
  - Person
default_form_display_components:
  - title
  - status
