_core:
  default_config_hash: 3LdRIR810EB_PT_SULILEUIsl-7MxMB1AFGCIw910OY
default_properties:
  estimatedSalary:
    type: MonetaryAmount
    properties:
      minValue: decimal
      maxValue: decimal
  nutrition:
    type: NutritionInformation
    properties:
      servingSize: string
      calories: decimal
      carbohydrateContent: decimal
      cholesterolContent: decimal
      fatContent: decimal
      fiberContent: decimal
      proteinContent: decimal
      saturatedFatContent: decimal
      sodiumContent: decimal
      sugarContent: decimal
      transFatContent: decimal
      unsaturatedFatContent: decimal
  FAQPage--mainEntity:
    type: Question
    properties:
      name: string_long
      acceptedAnswer: string_long
  QAPage--mainEntity:
    type: Question
    properties:
      name: string_long
      acceptedAnswer: string_long
default_format: basic_html
