_core:
  default_config_hash: 7UmLsGP-VG5AAk5PHa6D19bAvTamesMnDulclBzTTnY
property_order:
  - url
  - identifier
  - inDefinedTermSet
  - inLanguage
  - name
  - alternateName
  - headline
  - alternativeHeadline
  - givenName
  - additionalName
  - familyName
  - description
  - disambiguatingDescription
  - articleBody
  - text
  - author
  - image
  - photo
  - primaryImageOfPage
  - video
  - thumbnail
  - thumbnailUrl
  - contentUrl
  - address
  - addressCountry
  - addressRegion
  - addressLocality
  - postalCode
  - postOfficeBoxNumber
  - streetAddress
  - streetAddress
  - contactPoint
  - telephone
  - fax
  - email
  - startDate
  - endDate
  - duration
property_image_styles:
  image: large
  thumbnail: thumbnail
