<?php

/**
 * @file
 * Provides development tools for the Schema.org Blueprints module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Random;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\NodeType;
use Drupal\node\NodeInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;
use Drupal\schemadotorg\Entity\SchemaDotOrgMapping;

/**
 * Implements hook_entity_presave().
 */
function schemadotorg_devel_entity_presave(EntityInterface $entity): void {
  // Check that devel is generating a content entity.
  // @see https://www.drupal.org/project/devel/issues/2582845
  if (empty($entity->devel_generate)
    || !$entity instanceof ContentEntityInterface) {
    return;
  }

  $mapping = SchemaDotOrgMapping::loadByEntity($entity);
  if (!$mapping) {
    return;
  }

  // Get the mapping's properties keyed by property name.
  $schema_properties = array_flip($mapping->getSchemaProperties());

  // Get devel generate property values.
  $property_values = \Drupal::config('schemadotorg_devel.settings')
    ->get('generate_property_values');

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  $schema_type = $mapping->getSchemaType();

  // Limit node titles to two words with a max of 25 characters.
  if ($entity instanceof NodeInterface) {
    $random = new Random();
    $node_type = NodeType::load($entity->bundle())->label();
    $node_title = ucwords($random->word(mt_rand(1, 25)) . ' ' . $random->word(mt_rand(1, 25)));
    $entity->set('title', "$node_type - $node_title");
  }

  // Populate the fields.
  foreach ($property_values as $property => $values) {
    // Check Type--property.
    if (str_contains($property, '--')) {
      [$property_schema_type, $property] = explode('--', $property);
      if (!isset($schema_properties[$property])
        || !$schema_type_manager->isSubTypeOf($property_schema_type, $schema_type)) {
        continue;
      }
    }
    elseif (!isset($schema_properties[$property])) {
      continue;
    }

    $field_name = $schema_properties[$property];
    if (!$entity->hasField($field_name)) {
      continue;
    }

    /** @var \Drupal\Core\Field\FieldItemListInterface $field_item_list */
    $field_item_list = $entity->$field_name;

    if (empty($values)) {
      $field_item_list->setValue([]);
    }
    else {
      $main_property = $field_item_list
        ->getFieldDefinition()
        ->getFieldStorageDefinition()
        ->getMainPropertyName();
      foreach ($field_item_list as $item) {
        $item->set($main_property, $values[array_rand($values)]);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_devel_form_schemadotorg_general_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_devel'] = [
    '#type' => 'details',
    '#title' => t('Development settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
    '#weight' => 10,
  ];
  $form['schemadotorg_devel']['generate_property_values'] = [
    '#title' => t('Schema.org devel generate property values'),
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::INDEXED_GROUPED,
    '#settings_format' => 'propertyName|value01,value02,value03 or propertyName| or SchemaType--propertyName|value01,value02,value03 or SchemaType--propertyName|',
    '#description' => t('Enter Schema.org property values to be used when generating content using the Devel generate module.')
    . ' '
    . t('Leave blank to disable the generation of property values.'),
    '#description_link' => 'types',
  ];
}
