schemadotorg_paragraphs.settings:
  type: config_entity
  label: 'Schema.org Paragraphs settings'
  mapping:
    paragraphs_library:
      type: sequence
      label: 'Schema.org types that default to using the Paragraphs library'
      sequence:
        type: string
        label: 'Schema.org type'
    property_access:
      type: sequence
      label: 'Schema.org type property access'
      sequence:
        type: sequence
        label: 'Schema.org type'
        sequence:
          type: string
          label: 'Schema.org property'
