<?php

/**
 * @file
 * Manages translations for Schema.org types and properties as they are created.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\FieldConfigInterface;
use Drupal\schemadotorg\SchemaDotOrgMappingInterface;

/**
 * Implements hook_schemadotorg_mapping_insert().
 */
function schemadotorg_translation_schemadotorg_mapping_insert(SchemaDotOrgMappingInterface $mapping): void {
  if (\Drupal::isConfigSyncing()) {
    return;
  }

  /** @var \Drupal\schemadotorg_translation\SchemaDotOrgTranslationManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_translation.manager');
  $manager->enableMapping($mapping);
}

/**
 * Implements hook_field_config_insert().
 */
function schemadotorg_translation_field_config_insert(FieldConfigInterface $field_config): void {
  /** @var \Drupal\schemadotorg_translation\SchemaDotOrgTranslationManagerInterface $manager */
  $manager = \Drupal::service('schemadotorg_translation.manager');
  $manager->enableMappingField($field_config);
}

/* ************************************************************************** */
// Schema.org JSON-LD.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_type_entity_alter().
 */
function schemadotorg_translation_schemadotorg_jsonld_schema_type_entity_alter(array &$data, EntityInterface $entity): void {
  // Make sure the entity has Schema.org mapping.
  /** @var \Drupal\schemadotorg\SchemaDotOrgMappingInterface $mapping */
  $mapping = \Drupal::entityTypeManager()
    ->getStorage('schemadotorg_mapping')
    ->loadByEntity($entity);
  if (!$mapping) {
    return;
  }

  // Make sure we are dealing with a content entity with translations.
  if (!$entity instanceof ContentEntityInterface
    || empty($entity->getTranslationLanguages(FALSE))) {
    return;
  }

  // Check that Schema.org mapping type is a CreativeWork which
  // supports translations.
  // @see https://schema.org/workTranslation
  // @see https://schema.org/translationOfWork
  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  $schema_type = $mapping->getSchemaType();
  if (!$schema_type_manager->isSubTypeOf($schema_type, 'CreativeWork')) {
    return;
  }

  // Get current language translation for the entity.
  $current_langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $entity = $entity->getTranslation($current_langcode);

  if ($entity->isDefaultTranslation()) {
    // Default translation list all translations
    // using https://schema.org/workTranslation.
    $data['workTranslation'] = [];
    $translation_languages = $entity->getTranslationLanguages(FALSE);
    foreach ($translation_languages as $translation_language) {
      $translation = $entity->getTranslation($translation_language->getId());
      $data['workTranslation'][] = [
        '@type' => $data['@type'],
        '@id' => $translation->toUrl()->setAbsolute()->toString(),
      ];
    }
  }
  else {
    // Translation reference default
    // using https://schema.org/translationOfWork.
    // Get the default language.
    // Currently, Drupal does not provide an easy way to get this information.
    // @see \Drupal\Core\Entity\ContentEntityBase::$defaultLangcode
    $default_languages = array_diff_key(
      $entity->getTranslationLanguages(),
      $entity->getTranslationLanguages(FALSE)
    );
    $default_language = reset($default_languages);
    $default_translation = $entity->getTranslation($default_language->getId());
    $data['translationOfWork'] = ['@id' => $default_translation->toUrl()->setAbsolute()->toString()];
  }
}

/* ************************************************************************** */
// Schema.org general settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_translation_form_schemadotorg_general_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_translation'] = [
    '#type' => 'details',
    '#title' => t('Translation settings'),
  ];
  $form['schemadotorg_translation']['excluded_schema_types'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Excluded Schema.org types'),
    '#description' => t('Enter Schema.org types that should never be translated.'),
    '#description_link' => 'types',
    '#example' => '
- SchemaType01
- SchemaType02
- SchemaType03
',
  ];
  $form['schemadotorg_translation']['excluded_schema_properties'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Excluded Schema.org properties'),
    '#description' => t('Enter Schema.org properties that should never be translated.'),
    '#description_link' => 'properties',
    '#example' => '
- propertyName
- SchemaType--propertyName
',
  ];
  $form['schemadotorg_translation']['excluded_field_names'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Excluded field names'),
    '#description' => t('Enter field names that should never be translated.'),
    '#example' => '
- field_name_01
- field_name_02
- field_name_03
',
  ];
  $form['schemadotorg_translation']['included_field_names'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Included field names'),
    '#description' => t('Enter field names that should always be translated.'),
    '#example' => '
- field_name_01
- field_name_02
- field_name_03
',
  ];
  $form['schemadotorg_translation']['included_field_types'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Included field types'),
    '#description' => t('Enter field types that should always be translated.'),
    '#example' => '
- field_type_01
- field_type_02
- field_type_03
',
  ];
}
