smtp_on: true
smtp_host: smtp-relay.brevo.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: ssl
smtp_autotls: true
smtp_timeout: 300
smtp_username: 895deb001@smtp-brevo.com
smtp_password: q6VtUPvcWIy7CK2T
smtp_from: ''
smtp_fromname: ''
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: false
smtp_test_address: camoa2005@gmail.com
smtp_reroute_address: ''
smtp_debugging: false
smtp_debug_level: 1
smtp_keepalive: false
