plugin.plugin_configuration.geolocation.layer_feature.yandex_balloon:
  type: geolocation.layer_feature_settings
  label: 'Marker Balloon'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        info_auto_display:
          type: boolean
          label: 'Info Auto Display'
        disable_auto_pan:
          type: boolean
          label: 'Disable Auto Pan'
        max_width:
          type: integer
          label: 'Max Width'
        panel_max_map_area:
          type: string
          label: 'Panel max'
