schemadotorg_epp.settings:
  type: config_entity
  label: Schema.org Entity Prepopualte settings
  mapping:
    node_links:
      type: sequence
      label: 'Node Links'
      sequence:
        type: sequence
        label: 'Schema.org types'
        sequence:
          type: string
          label: 'Schema.org property/type.'
    node_links_dropdown:
      type: boolean
      label: 'Display node links as a dropdown'
