<?php

/**
 * @file
 * Primary module hooks for Markdown Easy module.
 */

declare(strict_types=1);

use League\CommonMark\Environment\Environment;
use League\CommonMark\Extension\Strikethrough\StrikethroughExtension;

/**
 * Implements hook_markdown_easy_config_modify().
 */
function markdown_easy_hook_test_markdown_easy_config_modify(array &$config): void {
  $config['html_input'] = 'allow';
  $config['allow_unsafe_links'] = TRUE;
}

/**
 * Implements hook_markdown_easy_environment_modify().
 */
function markdown_easy_hook_test_markdown_easy_environment_modify(Environment &$environment): void {
  $environment->addExtension(new StrikethroughExtension());
}
