filter_settings.markdown_easy:
  type: mapping
  label: 'Markdown Easy filter'
  mapping:
    flavor:
      type: string
      label: Flavor
markdown_easy.settings:
  type: config_object
  label: 'Markdown Easy settings'
  mapping:
    skip_filter_enforcement:
      type: boolean
      label: 'Skip filter enforcement'
    skip_html_input_stripping:
      type: boolean
      label: 'Skip HTML input stripping'
