<?php

/**
 * @file
 * Module file for the Klaro! module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_page_attachments().
 */
function klaro_page_attachments(array &$page) {

  $helper = \Drupal::service('klaro.helper');
  $config = $helper->getSettings();
  $config_texts = $helper->getTexts();
  $renderer = $helper->getRenderer();
  // Updating klaro config will update cache.
  $renderer->addCacheableDependency($page, $config);
  $renderer->addCacheableDependency($page, $config_texts);
  // Cases in which klaro library will not be added.
  if (!$helper->hasAccess() || $helper->onDisabledUri() || $helper->onExcludedUri()) {
    return;
  }
  $page['#attached']['drupalSettings']['klaro'] = $helper->processDrupalSettings();
  $page['#attached']['library'][] = 'klaro/klaro';

}

/**
 * Implements hook_module_implements_alter().
 */
function klaro_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    case 'js_alter':
    case 'page_attachments_alter':
      // Ensure our hooks run last to support libraries added by other modules.
      $group = $implementations['klaro'];
      unset($implementations['klaro']);
      $implementations['klaro'] = $group;
      break;
  }
}

/**
 * Implements hook_js_alter().
 *
 * Handles script files added from libraries.
 */
function klaro_js_alter(&$javascript, AttachedAssetsInterface $assets) {
  // @todo The assets are cached based on theme, library, langcode etc. so we
  // cannot differ based on user permissions.
  // @see \Drupal\Core\Asset\AssetResolver::getJsAssets
  /** @var \Drupal\klaro\Utility\KlaroHelper $helper */
  $helper = \Drupal::service('klaro.helper');

  if (!$helper->hasAccess() || $helper->onDisabledUri() || !$helper->getSettings()->get('auto_decorate_js_alter')) {
    return;
  }

  $source_apps = [];
  foreach ($helper->getApps() as $klaro_app) {
    foreach ((array) $klaro_app->javascripts() as $string) {
      $source_apps[$string] = $klaro_app->id();
    }
  }

  foreach ($javascript as $path => &$script) {
    foreach ($source_apps as $source => $app_id) {
      if ($script['type'] === 'setting' || strpos($path, $source) === FALSE) {
        continue;
      }
      $script['preprocess'] = FALSE;
      $script['klaro'] = $app_id;
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 *
 * Handles manually attached JS files.
 */
function klaro_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\klaro\Utility\KlaroHelper $helper */
  $helper = \Drupal::service('klaro.helper');
  if (!$helper->hasAccess() || $helper->onDisabledUri() || !$helper->getSettings()->get('auto_decorate_page_attachments')) {
    return;
  }
  /** @var \Drupal\Core\Render\Renderer $renderer */
  $renderer = $helper->getRenderer();

  $attachment_apps = [];
  foreach ($helper->getApps() as $klaro_app) {
    foreach ($klaro_app->attachments() as $attachment) {
      $attachment_apps[$attachment] = $klaro_app->id();
    }
    $renderer->addCacheableDependency($attachments, $klaro_app);
  }

  foreach ($attachments['#attached']['html_head'] as &$attached_html_head) {
    $item = &$attached_html_head[0];
    $identifier = $attached_html_head[1] ?? '';
    if (!$identifier || !isset($attachment_apps[$identifier])) {
      continue;
    }

    $item['#attributes']['type'] = 'text/plain';
    $item['#attributes']['data-type'] = 'application/javascript';
    $item['#attributes']['data-name'] = $attachment_apps[$identifier];
    if (isset($item['#attributes']['src'])) {
      $item['#attributes']['data-src'] = $item['#attributes']['src'];
      unset($item['#attributes']['src']);
    }
  }
}

/**
 * Implements hook_library_info_alter().
 */
function klaro_library_info_alter(&$libraries, $extension) {

  if ($extension !== 'klaro') {
    return;
  }

  /** @var \Drupal\klaro\Utility\KlaroHelper $helper */
  $helper = \Drupal::service('klaro.helper');

  if ($helper->hasLibraryFiles()) {
    return;
  }
  elseif (!$helper->hasDeprecatedLibraryFiles()) {
    // Klaro library not found.
    $message = "The klaro-js library is not found at libraries folder, please read the install instructions in the README of the klaro drupal module.";
    \Drupal::logger('klaro')->error($message);
  }
  else {
    // Backwards compatibility for "old" library-name "klaro"
    // https://www.drupal.org/project/klaro/issues/3428601
    $libraries['library']['js']['/libraries/klaro/dist/klaro-no-css.js'] = $libraries['library']['js']['/libraries/klaro-js/dist/klaro-no-css.js'];
    $libraries['library']['css']['base']['/libraries/klaro/dist/klaro.min.css'] = $libraries['library']['css']['base']['/libraries/klaro-js/dist/klaro.min.css'];
    unset($libraries['library']['js']['/libraries/klaro-js/dist/klaro-no-css.js']);
    unset($libraries['library']['css']['base']['/libraries/klaro-js/dist/klaro.min.css']);
  }

}
