<?php

/**
 * @file
 * Contains install and update functions for klaro.
 */

/**
 * Update settings and permissions.
 */
function klaro_update_8201() {
  $config_factory = \Drupal::configFactory();

  $config_settings = $config_factory->getEditable('klaro.settings');
  $config_texts = $config_factory->getEditable('klaro.texts');

  // Update settings.
  $config_texts->set('consentModal.privacyPolicy.url', $config_settings->get('library.privacy_policy'));
  $config_settings->clear('library.privacy_policy');
  $config_settings->set('auto_show', $config_settings->get('enabled'));
  $config_settings->clear('enabled');
  // @todo Write update notice for users wanting "no-css" feature.
  $config_settings->clear('klaro_library');

  $config_settings->save(TRUE);
  $config_texts->save(TRUE);

  // Update permissions.
  $roles = \Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  foreach ($roles as $role) {
    if ($role->hasPermission('bypass klaro')) {
      $role->revokePermission('bypass klaro');
    }
    else {
      $role->grantPermission('use klaro');
    }
    $role->save();
  }
}

/**
 * Update to 3.0.0.
 */
function klaro_update_10001(&$sandbox) {
  $config_factory = \Drupal::configFactory();
  $config_settings = $config_factory->getEditable('klaro.settings');
  $config_texts = $config_factory->getEditable('klaro.texts');

  // Set new config settings.
  $config_settings->set('block_unknown', TRUE);
  $config_settings->set('auto_decorate_js_alter', TRUE);
  $config_settings->set('auto_decorate_page_attachments', TRUE);
  $config_settings->set('auto_decorate_final_html', TRUE);
  $config_settings->set('show_toggle_button', TRUE);
  $config_settings->set('block_unknown_label', 'Unknown app');
  $config_settings->set('block_unknown_description', 'Unknown description');

  // Remove old config settings.
  $config_settings->clear('auto_show');

  $config_settings->save(TRUE);

  // Add new texts.
  $config_texts->set('contextualConsent.acceptAlways', 'Always');
  $config_texts->set('contextualConsent.acceptOnce', 'Yes');
  $config_texts->set('contextualConsent.description', 'Do you want to load external content supplied by {title}?');

  $config_texts->save();

}

/**
 * Remove obsolete auto_show setting.
 */
function klaro_update_10002() {
  $config = \Drupal::configFactory()->getEditable('klaro.settings');
  $config->clear('auto_show')->save(TRUE);
}

/**
 * Issue #3483378: Add option for preprocess_field.
 */
function klaro_update_10005(&$sandbox) {
  $config_factory = \Drupal::configFactory();
  $config_settings = $config_factory->getEditable('klaro.settings');

  // Set new config setting.
  $config_settings->set('auto_decorate_preprocess_field', TRUE);

  $config_settings->save(TRUE);

}

/**
 * Issue #3476193: Rename log unknown services.
 */
function klaro_update_10006(&$sandbox) {
  $config_factory = \Drupal::configFactory();
  $config_settings = $config_factory->getEditable('klaro.settings');

  $data = $config_settings->get('block_unknown_logger');
  // Set new config setting.
  $config_settings->set('log_unknown_resources', $data);
  $config_settings->save(TRUE);
  $config_settings->clear('block_unknown_logger')->save(TRUE);

}
