schemadotorg_focal_point.settings:
  type: config_entity
  label: 'Schema.org Focal point settings'
  mapping:
    image_styles:
      type: sequence
      label: 'Image styles'
      sequence:
        type: mapping
        label: 'Image style'
        mapping:
          ratio:
            type: string
            label: Ratio
          max-width:
            type: integer
            label: Max-width
          min-width:
            type: integer
            label: Min-width
          increment:
            type: integer
            label: Increment
