<?php

/**
 * @file
 * Allows Existing Values Autocomplete Widgets to be used to create Schema.org relationships.
 */

declare(strict_types = 1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\schemadotorg\Element\SchemaDotOrgSettings;

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_existing_values_autocomplete_widget_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings
): void {
  if ($field_storage_values['type'] !== 'string') {
    return;
  }

  $default_properties = \Drupal::config('schemadotorg_existing_values_autocomplete_widget.settings')
    ->get("default_properties");
  if (in_array($schema_property, $default_properties)) {
    $widget_id = 'existing_autocomplete_field_widget';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function schemadotorg_existing_values_autocomplete_widget_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_existing_values_autocomplete_widget'] = [
    '#type' => 'details',
    '#title' => t('Existing values autocomplete widget settings'),
    '#open' => TRUE,
    '#tree' => TRUE,
  ];
  $form['schemadotorg_existing_values_autocomplete_widget']['default_properties'] = [
    '#type' => 'schemadotorg_settings',
    '#settings_type' => SchemaDotOrgSettings::INDEXED,
    '#settings_format' => 'propertyName',
    '#title' => t('Default Existing Values Autocomplete Widget properties'),
    '#description' => t('Enter Schema.org properties that should use the Existing Values Autocomplete Widget.'),
    '#description_link' => 'properties',
  ];
}
