schemadotorg_sidebar.settings:
  type: config_entity
  label: 'Schema.org Sidebar settings'
  mapping:
    paragraph_types:
      type: sequence
      label: 'Sidebar paragraph types'
      sequence:
        type: sequence
        label: 'Sidebar Schema.org types'
        sequence:
          type: string
          label: 'Sidebar Schema.org type'
