plugin.plugin_configuration.geolocation.map_center_option.fit_bounds:
  type: geolocation.map_center_option_settings
  label: 'Fit Locations'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        reset_zoom:
          type: boolean
          label: 'Reset zoom'
        min_zoom:
          type: integer
          label: 'Min zoom'

plugin.plugin_configuration.geolocation.map_center_option.fit_shapes:
  type: geolocation.map_center_option_settings
  label: 'Fit Shapes'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        min_zoom:
          type: integer
          label: 'Min zoom'

plugin.plugin_configuration.geolocation.map_center_option.fixed_boundaries:
  type: geolocation.map_center_option_settings
  label: 'Fixed boundaries'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        south:
          type: string
          label: 'South'
        west:
          type: string
          label: 'West'
        north:
          type: string
          label: 'North'
        east:
          type: string
          label: 'East'

plugin.plugin_configuration.geolocation.map_center_option.views_boundary_filter:
  type: geolocation.map_center_option_settings
  label: 'Boundary filter'
  mapping:
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        clear_address_input:
          type: boolean
          label: 'Clear address input on map bound change'


plugin.plugin_configuration.geolocation.map_center_option.location_plugins:
  type: plugin.plugin_configuration.geolocation.location.[settings.location_option_id]
  label: 'Location Option'
  mapping:
    map_center_id:
      type: string
      label: 'Fixed Map Center ID'

