field.formatter.settings.geolocation_geometry:
  type: field.formatter.settings.geolocation_map
  label: 'Geolocation Geometry Formatter'
  mapping:
    data_provider_settings:
      label: 'Data provider settings'
      type: geolocation.data_provider.geolocation_geometry

field.formatter.settings.geolocation_geometry_data:
  type: mapping
  label: 'Geolocation Geometry Data Formatter'
  mapping:
    geometry_format:
      type: string
      label: 'Format'

field.formatter.settings.geolocation_geometry_file:
  type: mapping
  label: 'Geolocation Geometry File Formatter'
  mapping:
    geometry_format:
      type: string
      label: 'Format'
